FROM ubuntu:20.04
ENV TZ=Europe/Warsaw
RUN apt update && apt-get install -y g++ cmake libpcre3-dev zlib1g-dev libgcrypt-dev libicu-dev python && apt-get install --no-install-recommends qtbase5-dev libpng-dev openjdk-11-jre
